---
- name: verification
  hosts: all
  become: false
  gather_facts: false

  roles:
    - aac/create_attribute
    - aac/create_obligation
    - aac/delete_attribute
    - aac/disable_authentication_policies
    - aac/get_mapping_rules
    - aac/set_access_policies
    - aac/configure_access_control_attributes
    - aac/configure_access_control_policies
    - aac/configure_access_control_policy_attachments
    - aac/configure_access_control_policy_resources
    - aac/configure_api_protection_clients
    - aac/configure_api_protection_definitions
    - aac/configure_authentication_mechanisms
    - aac/configure_authentication_policies
    - aac/configure_mapping_rules
    - aac/configure_runtime_template_root
    - aac/configure_scim
    - aac/configure_server_connections
    - aac/configure_user_registry
    - aac/create_api_protection_clients
    - aac/create_api_protection_definitions
    - aac/create_authentication_mechanisms
    - aac/create_authentication_policies
    - aac/create_user_registry_user
    - aac/disable_all_authentication_policies
    - aac/export_runtime_template_root
    - aac/get_accesscontrol_configuration
    - aac/set_accesscontrol_policies
    - aac/set_accesscontrol_policyattachment
    - aac/update_advanced_configurations
    - aac/update_api_protection_clients
    - activate_module
    - add_attribute_source
    - add_chain_template
    - add_cluster_node
    - add_federation
    - add_junction
    - add_junction_servers
    - add_mgmtazn_role
    - add_module_chain
    - add_network_ipv4
    - add_oauth_client
    - add_oauth_definition
    - add_partner
    - add_reverseproxy_conf
    - add_runtime_listening_interface
    - add_server_connection_ldap
    - add_server_connection_ws
    - add_static_route
    - add_suffix
    - add_sysaccount_group
    - add_sysaccount_user
    - add_system_alerts_rsyslog
    - add_system_alerts_smtp
    - add_system_alerts_snmp
    - archive_logs
    - authenticate_policy_attachments
    - base/activate_modules
    - base/add_bonding_interfaces
    - base/add_interfaces
    - base/apply_snapshot
    - base/backup_firmware
    - base/bonding_interfaces
    - base/change_admin_password
    - base/configure_advanced_tuning_parameters
    - base/configure_cluster
    - base/configure_dhcp
    - base/configure_interfaces
    - base/configure_runtime_tunings
    - base/configure_time
    - base/create_snapshot
    - base/create_ssl_certificate_databases
    - base/create_sysaccounts
    - base/delete_interfaces
    - base/delete_snapshots
    - base/download_snapshots
    - base/export_certificates
    - base/externalize_hvdb
    - base/extract_certificates
    - base/first_steps
    - base/generate_self_signed_certificates
    - base/get_certificate_databases
    - base/get_personal_certificates
    - base/get_signer_certificates
    - base/import_personal_certificates
    - base/import_signer_certificates
    - base/install_fixpacks
    - base/install_update
    - base/load_signer_certificates
    - base/set_host_records
    - base/set_listening_interfaces
    - base/swap_firmware
    - base/upload_signer_certificates
    - base/upload_snapshot
    - base/upload_updates
    - bootstrap_local
    - config_dns
    - config_failover_cookie
    - config_fed_dir
    - config_ntp
    - config_policy_attachments
    - config_policyserver
    - config_reverseproxy_aac
    - config_reverseproxy_federation
    - config_reverseproxy_oauth
    - config_snmp_monitoring
    - create_keystore
    - create_mgmt_root_dir
    - create_mgmt_root_file
    - create_reverseproxy
    - create_runtime_template_directories
    - create_snapshot
    - delete_activation
    - delete_mgmt_root_file
    - delete_reverseproxy_conf
    - execute_compare
    - execute_isamcfg
    - execute_pdadmin
    - execute_rp_op
    - export_application_logs
    - export_cluster_sign
    - externalize_hvdb_db2
    - fed/configure_instance_federations
    - fed/configure_sts_chains
    - fed/configure_sts_chain_templates
    - fed/create_federation_partners
    - fed/create_federations
    - fed/get_federation_partners
    - fed/get_federations
    - fed/set_runtime_certificates
    - first_steps
    - fed/set_attribute_source
    - gen_report
    - get_federation
    - get_firmware
    - get_fixpack
    - get_junction_details
    - get_junctions
    - get_reverseproxies
    - import_ca_certs
    - import_client_cert_mapping
    - import_http_transformation
    - import_management_root
    - import_personal_cert
    - import_runtime_template_file
    - import_url_mapping
    - install_firmware
    - install_fixpack
    - install_license
    - load_signer_cert
    - meta
    - sanity_checks
    - search_attribute_source
    - search_mapping_rule
    - set_access_control_policy
    - set_admin_cfg
    - set_admin_pw
    - set_advanced_tuning_parameter
    - set_audit_configuration
    - set_auth_mech
    - set_auth_policy
    - set_cert_replication
    - set_cluster_config
    - set_current_point_of_contact
    - set_federation
    - set_host_records
    - set_junction
    - set_keystore_desc
    - set_ldap_root_pw
    - set_ldap_user_attr
    - set_ldap_user_pw
    - set_mapping_rule
    - set_mgmtazn_role_feature
    - set_network_hostname
    - set_network_ipv4_dhcp
    - set_oauth_client
    - set_oauth_definition
    - set_partner
    - set_reverseproxy_conf
    - set_rsyslog_forwarder
    - set_rsyslog_forwarder_sources
    - set_runtime_replication
    - set_runtime_tuning_parameter
    - set_tcpip_tuning
    - start_config
    - switch_auth
    - update_advanced_configuration
    - update_auth_mech
    - update_management_root
    - update_management_ssl_cert
    - update_network_interface_vlan
    - update_network_ipv4
    - update_point_of_contact
    - update_reverseproxy_conf
    - update_static_route
    - upload_extension
    - upload_ltpa_key
    - upload_mapping_rule
    - web/merge_keytabs
    - web/upload_kerberos_keytab_files
    - web/configure_federated_directories
    - web/configure_management_root
    - web/configure_policyserver
    - web/configure_reverseproxy_instances
    - web/configure_reverseproxy_junctions
    - web/configure_runtime_components
    - web/create_reverseproxy_instances
    - web/create_sso_keys
    - web/execute_pdadmin
    - web/export_sso_keys
    - web/import_certificate_mapping_files
    - web/import_sso_keys
    - web/restart_reverseproxy_instance
    - web/set_embedded_ldap_admin_pw
    - web/set_runtime_components
    - web/update_jmt_files
    - web/upload_dynurl_files
    - web/upload_http_transformation_files
    - web/upload_jmt_files
    - web/upload_ltpa_files
    - web/upload_management_root_files
    - web/upload_runtime_components
